version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 3
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = true
beaconBeamCulling = true
entityModelCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
create_new_age = true
farmersdelight = true
createdeco = true
create_jetpack = true
create_enchantment_industry = true
origins = true
railways = true
sliceanddice = true
waystones = true
milk = true
create = true
copycats = true
minecraft = true
creategoggles = true
